import swaggerJSDoc from "swagger-jsdoc";

const swaggerDefinition = {
  openapi: "3.0.0", // Versi Swagger yang digunakan
  info: {
    title: "API Documentation", // Judul API
    version: "1.0.0", // Versi API
    description: "Express API with autogenerated swagger doc", // Deskripsi API
  },
  servers: [
    {
      url: "http://localhost:3000", // URL API Anda
    },
  ],
};

const options = {
  swaggerDefinition,
  // Path untuk file yang berisi anotasi Swagger
  apis: ["./src/routes/*.js"], // Sesuaikan dengan struktur proyek Anda
};

const swaggerSpec = swaggerJSDoc(options);

export default swaggerSpec;
